name : Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    
    - name: Check out the code
      uses: actions/checkout@v3
      
    - name: Set up Git
      run: |
        git config --global user.name "aadilsnovasys"
        git config --global user.email "aadilraza@snovasys.com"

    - name: Create or Checkout Github Pages
      run: |
        git checkout --orphan gh-pages
        

    - name: Copy files to gh-pages branch
      run: |
        cp -r * ./

    - name: Commit and Push to Github Pages
      run: |
        git add --all
        git commit -m "Deploy to Github Pages"
        git push --force --set-upstream origin gh-pages
        
